#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

source /etc/environment
if [[ -z "${EDH_CLUSTER_ID}" ]]; then
  echo "EDH_CLUSTER_ID environment variable not found."
  exit 1
else
  source "/opt/edh/${EDH_CLUSTER_ID}/python/latest/edh_python.env"
  "/opt/edh/${EDH_CLUSTER_ID}/python/latest/bin/python3" "$@"
fi